language: php

php:
  - 7.0

install:
  - travis_retry composer self-update
  - travis_retry composer clear-cache
  - travis_retry composer update

script:
  - php php/crawler/crawler.class.php
  - php php/search/search.inc.php
  - php php/search/results_display.inc.php
  - php php/crawl.php
  - php php/start_crawler.php

matrix:
 fast_finish: true
